fix: `id` is not used in object type (probably legacy from SDKv2 example) see full error below
        Error: Value Conversion Error

          with data.hashicups_coffees.test,
        An unexpected error was encountered trying to convert from struct into an
        object. This is always an error in the provider. Please report the following
        to the provider developer:

        Mismatch between struct and object type: Object defines fields not found in
        struct: id.
        Struct: provider.coffeesDataSourceModel
        Object type:
        types.ObjectType["coffees":types.ListType[types.ObjectType["description":basetypes.StringType,
        "id":basetypes.Int64Type, "image":basetypes.StringType,
        "ingredients":types.ListType[types.ObjectType["id":basetypes.Int64Type]],
        "name":basetypes.StringType, "price":basetypes.Float64Type,
        "teaser":basetypes.StringType]], "id":basetypes.StringType]